### ISSUE TITLE
Show diff for commits without parent / initial commit

### ISSUE THREAD

**Issue by mlange-42** [mlange-42/git-igitt#5]
Currently, no diffs/changed files are shown for the initial commit of a repository.

Unclear how to access the diffs via `git2`/`libgit2`. Somehow compate to hash `0000000`?

**Comment by adamreichold** [comment]
AFAIU, [`Repository::diff_tree_to_tree`](https://docs.rs/git2/0.13.15/git2/struct.Repository.html#method.diff_tree_to_tree) takes `Option<&Tree<'_>>` where `None` specifies an empty tree, so the initial diff would be `initial_commit.tree().unwrap()` for `new_tree` and `None` for `old_tree`?

**Comment by mlange-42** [comment]
Yes, I also realized this last night. In a short trial I had problems with the borrow checker, but it probably was just too late 😄
