### ISSUE TITLE
Alpine linux support

### ISSUE THREAD

**Issue by ADIX7** [mlange-42/git-igitt#58]
Can you create releases for Alpine linux (musl based distro(s)) ? Such a good application, it would be great to use on my Alpine based servers!

**Comment by mlange-42** [comment]
Could you please check if the resp. binaries at the bottom of [this action](https://github.com/mlange-42/git-igitt/actions/runs/3924631581) would work for you?

**Comment by ADIX7** [comment]
Yes, it works!

**Comment by mlange-42** [comment]
Ok, cool. Thanks for testing. Will add it to the release builds.

**Comment by mlange-42** [comment]
You can download Alpine binaries from the [releases](https://github.com/mlange-42/git-igitt/releases/) from now on.
